name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # Daily at midnight.

jobs:
  build-and-deploy:
    runs-on: macos-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - run: zig build

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./zig-out/www
      - uses: actions/deploy-pages@v4
